### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [NonLogicalDev/shell.async-goprompt#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by NonLogicalDev** [comment]
@unixorn My bad, will do. And thank you, happy to make the list =]

**Comment by NonLogicalDev** [comment]
@unixorn I added the `LICENCE` file and improved the documentation of the project if you want to have another look =]

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/1685
